import type { Metadata } from "next";
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import AuthWrapper from "@/components/AuthWrapper";
import { isAuthenticated } from "@/auth";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kayco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authenticated = isAuthenticated();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthWrapper isAuthenticated={authenticated}>
          <Navbar/>
          {children}
          <Footer/>
        </AuthWrapper>
      </body>
    </html>
  );
}
